name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at 00:00 UTC
  workflow_dispatch:      # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Manoj2134   # <-- change if your username is different
          outputs: |
            dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
